# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config
from typing import Literal


@config.config
class CheckmarxSourceConfig(config.Config):
    tenant_name: str
    api_key: str
    region: Literal["us", "us2", "eu", "eu2", "deu", "anz", "ind", "sng", "mea"] = config.value(default="us")
