# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config
from typing import Literal


@config.config
class CoverallsSourceConfig(config.Config):
    repositories: str
    service: Literal["github", "gitlab", "bitbucket"] = config.value(default="github")
    api_token: str | None = None
