# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config
from typing import Literal


@config.config
class SumoLogicSourceConfig(config.Config):
    access_id: str
    access_key: str
    deployment: Literal["us1", "us2", "au", "ca", "de", "eu", "fed", "in", "jp", "kr"] = config.value(default="us1")
    search_query: str | None = None
