# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config
from typing import Literal


@config.config
class VeracodeSourceConfig(config.Config):
    api_id: str
    api_secret: str
    region: Literal["com", "eu", "us"] = config.value(default="com")
